//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: daily-receipt (cli)
//! AC description: Rendering is deterministic: two `render` invocations with byte-identical summary+content JSON produce byte-identical ESC/POS output (no timestamps, no RNG, no map iteration order leaking in).
//! Test predicate: tests/acceptance_ac3.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac3` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown, clippy::indexing_slicing, clippy::manual_string_new, clippy::missing_panics_doc)]

mod common;

use daily_receipt::render;

#[test]
fn acceptance_ac3() {
    let summary = common::workday_summary();
    let content = common::haiku_content();
    let a = render(&summary, &content).expect("render a");
    let b = render(&summary, &content).expect("render b");
    assert_eq!(a, b, "workday render is not deterministic");

    let summary = common::quiet_summary();
    let content = common::glyph_content(0xDEAD_BEEF);
    let a = render(&summary, &content).expect("render glyph a");
    let b = render(&summary, &content).expect("render glyph b");
    assert_eq!(a, b, "quiet glyph render is not deterministic");

    let summary = common::special_summary();
    let content = common::stamp_content("birthday");
    let a = render(&summary, &content).expect("render stamp a");
    let b = render(&summary, &content).expect("render stamp b");
    assert_eq!(a, b, "special stamp render is not deterministic");
}
