//! Acceptance test for AC2 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: daily-receipt (cli)
//! AC description: Output bytes begin with the ESC/POS init sequence ESC '@' (0x1B 0x40) and end with a feed-and-cut sequence (GS V 0x42 0x00 = 0x1D 0x56 0x42 0x00). This is the printer-handshake contract every strip must honor.
//! Test predicate: tests/acceptance_ac2.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac2` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown, clippy::indexing_slicing, clippy::manual_string_new, clippy::missing_panics_doc)]

mod common;

use daily_receipt::render;

#[test]
fn acceptance_ac2() {
    // Workday haiku strip.
    let bytes = render(&common::workday_summary(), &common::haiku_content()).expect("render workday");
    assert_eq!(&bytes[..2], &[0x1B, 0x40], "ESC @ init prefix missing");
    assert_eq!(
        &bytes[bytes.len() - 4..],
        &[0x1D, 0x56, 0x42, 0x00],
        "GS V B 0 feed-and-cut suffix missing"
    );

    // Quiet glyph strip.
    let bytes = render(&common::quiet_summary(), &common::glyph_content(42)).expect("render quiet");
    assert_eq!(&bytes[..2], &[0x1B, 0x40]);
    assert_eq!(&bytes[bytes.len() - 4..], &[0x1D, 0x56, 0x42, 0x00]);

    // Special stamp strip.
    let bytes =
        render(&common::special_summary(), &common::stamp_content("birthday")).expect("render special");
    assert_eq!(&bytes[..2], &[0x1B, 0x40]);
    assert_eq!(&bytes[bytes.len() - 4..], &[0x1D, 0x56, 0x42, 0x00]);
}
