//! Acceptance test for AC5 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: daily-receipt (cli)
//! AC description: Haiku content must be exactly three lines, each line 1..=40 visible chars. `render` returns an error (exit code 3) when the content payload has the wrong shape for the day-type. No silent truncation, no panic.
//! Test predicate: tests/acceptance_ac5.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac5` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown, clippy::indexing_slicing, clippy::manual_string_new, clippy::missing_panics_doc)]

mod common;

use std::process::Command;

use daily_receipt::{Content, render};

#[test]
fn acceptance_ac5() {
    // Empty line -> HaikuShape (exit code 3).
    let bad = Content::Haiku {
        lines: ["".into(), "ok".into(), "ok".into()],
    };
    let err = render(&common::workday_summary(), &bad).unwrap_err();
    assert_eq!(err.exit_code(), 3, "empty line should be exit 3");

    // Overlong line (>40 chars) -> HaikuShape.
    let bad = Content::Haiku {
        lines: [
            "x".repeat(41),
            "ok line two".into(),
            "ok line three".into(),
        ],
    };
    let err = render(&common::workday_summary(), &bad).unwrap_err();
    assert_eq!(err.exit_code(), 3, "overlong line should be exit 3");

    // Wrong shape for day-type — workday with glyph content -> ContentShape (exit 3).
    let err = render(&common::workday_summary(), &common::glyph_content(1)).unwrap_err();
    assert_eq!(err.exit_code(), 3, "workday + glyph should be exit 3");

    // Now drive the CLI to confirm the exit code actually surfaces.
    let dir = common::tmp_dir("ac5");
    let summary_path = common::write_json(&dir, "summary.json", &common::workday_summary());
    let bad_content = Content::Haiku {
        lines: ["".into(), "ok".into(), "ok".into()],
    };
    let content_path = common::write_json(&dir, "content.json", &bad_content);
    let out_path = dir.join("strip.escpos");
    let status = Command::new(common::cli_bin())
        .arg("render")
        .arg("--summary")
        .arg(&summary_path)
        .arg("--content")
        .arg(&content_path)
        .arg("--out")
        .arg(&out_path)
        .status()
        .expect("spawn cli");
    assert_eq!(status.code(), Some(3), "cli should exit 3 on haiku shape error");
}
