//! Acceptance test for AC4 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: daily-receipt (cli)
//! AC description: Day-type classifier `classify` returns `workday` when summary has >=3 distinct repos OR >=10 commits, `special` when summary.special_stamp_id is set, and `quiet` otherwise. Exhaustive on the three variants; no fourth bucket.
//! Test predicate: tests/acceptance_ac4.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac4` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac4() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC4 not yet implemented — see file header");
}
